name: TwitterHD
options:
  bundleIdPrefix: com.sanfangx
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
    ASSETCATALOG_COMPILER_APPICON_NAME: ""
targets:
  TwitterHD:
    type: application
    platform: iOS
    sources: TwitterHD
    dependencies:
      - framework: WebKit.framework
      - framework: Photos.framework
      - framework: UniformTypeIdentifiers.framework
    settings:
      base:
        INFOPLIST_FILE: TwitterHD/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.sanfangx.twitterhd
        TARGETED_DEVICE_FAMILY: "1"
        CODE_SIGN_STYLE: Manual
        CODE_SIGNING_ALLOWED: "NO"
        CODE_SIGNING_REQUIRED: "NO"
        DEVELOPMENT_TEAM: ""
